context:
  version: "0.0.7"

package:
  name: nb-cli
  version: ${{ version }}

source:
  url: https://github.com/jupyter-ai-contrib/nb-cli/archive/v${{ version }}.tar.gz
  sha256: 815391f36889437909156b81f03c685bd437c32a3007d59b6c072b10a8842a7a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - nb --help
      - nb --version

about:
  homepage: https://github.com/jupyter-ai-contrib/nb-cli
  repository: https://github.com/jupyter-ai-contrib/nb-cli
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "A command-line tool for reading, writing, and executing Jupyter notebooks"

extra:
  recipe-maintainers:
    - 3coins
    - andrii-i
    - ellisonbg
